local SolarisLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/Stebulous/solaris-ui-lib/main/source.lua"))()

--[[SolarisLib:New({
  Name - Title of the UI <string>
  FolderToSave - Name of the folder where the UI files will be stored <string>
})]]
local win = SolarisLib:New({
  Name = "[UPD 2!] Anime Speed Simulator",
  FolderToSave = "SolarisLibStuff"
})

--win:Tab(title <string>)
local tab = win:Tab("Training")

--tab:Section(title <string>)
local sec = tab:Section("TrainingClick")

local Weight = sec:Toggle("Training", false,"Toggle", function(t)
  _G.Training = t
while _G.Training == true do
    -- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").Events.Training:FireServer()

wait()
end
end)

local Weight = sec:Toggle("Rebirth", false,"Toggle", function(t)
  _G.Rebirth = t
while _G.Rebirth == true do
    -- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").Events.Rebirth:FireServer()

wait()
end
end)

--Hatch_All
--win:Tab(title <string>)
local tab = win:Tab("Hatch_All")

--tab:Section(title <string>)
local sec = tab:Section("Hatch")
--DragonStar
local Weight = sec:Toggle("DragonStar", false,"Toggle", function(t)
  _G.Hatch = t
while _G.Hatch == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "DragonStarDispenser"
}

game:GetService("ReplicatedStorage").Events.Hatch:FireServer(unpack(args))

wait()
end
end)

--ShinobiStar
local Weight = sec:Toggle("ShinobiStar", false,"Toggle", function(t)
  _G.Hatch = t
while _G.Hatch == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "ShinobiStarDispenser"
}

game:GetService("ReplicatedStorage").Events.Hatch:FireServer(unpack(args))

wait()
end
end)

--PirateStar
local Weight = sec:Toggle("PirateStar", false,"Toggle", function(t)
  _G.Hatch = t
while _G.Hatch == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "PirateStarDispenser"
}

game:GetService("ReplicatedStorage").Events.Hatch:FireServer(unpack(args))

wait()
end
end)

--DemonStar
local Weight = sec:Toggle("DemonStar", false,"Toggle", function(t)
  _G.Hatch = t
while _G.Hatch == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "DemonStarDispenser"
}

game:GetService("ReplicatedStorage").Events.Hatch:FireServer(unpack(args))

wait()
end
end)

--PunchStar
local Weight = sec:Toggle("PunchStar", false,"Toggle", function(t)
  _G.Hatch = t
while _G.Hatch == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "PunchStarDispenser"
}

game:GetService("ReplicatedStorage").Events.Hatch:FireServer(unpack(args))

wait()
end
end)

---BringHoops
--win:Tab(title <string>)
local tab = win:Tab("Bring_Hoops")

--tab:Section(title <string>)
local sec = tab:Section("Auto Hoops")

local Weight = sec:Toggle("Meadows Hoops", false,"Toggle", function(t)
  _G.Hoops = t
while _G.Hoops == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop1
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop2
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop3
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop4
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop5
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop6
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop7
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop8
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop9
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop10
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop11
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop12
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Meadows.Hoops.Hoop13
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))

wait()
end
end)

--Arctic
local Weight = sec:Toggle("Arctic Hoops", false,"Toggle", function(t)
  _G.Hoops = t
while _G.Hoops == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop1
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop2
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop3
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop4
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop5
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop6
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop7
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop8
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop9
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop10
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop11
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop12
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop13
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop14
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop15
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop16
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop17
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop18
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop19
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))

wait()
end
end)

--Oasis
local Weight = sec:Toggle("Oasis Hoops", false,"Toggle", function(t)
  _G.Hoops = t
while _G.Hoops == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop1
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop2
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop3
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop4
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop5
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop6
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop7
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop8
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop9
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop10
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop11
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop12
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop13
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop14
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop15
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop16
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop17
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop18
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop19
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop20
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Oasis.Hoops.Hoop21
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))

wait()
end
end)

--Underworld
local Weight = sec:Toggle("Underworld Hoops", false,"Toggle", function(t)
  _G.Hoops = t
while _G.Hoops == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop1
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop2
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop3
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop4
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop5
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop6
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop7
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop8
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop9
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop10
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop11
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop12
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop13
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop14
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop15
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop16
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop17
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop18
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop19
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop20
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop21
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop22
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop23
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Underworld.Hoops.Hoop24
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))

wait()
end
end)

--Arctic
local Weight = sec:Toggle("Arctic Hoops", false,"Toggle", function(t)
  _G.Hoops = t
while _G.Hoops == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop1
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop2
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop3
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop4
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop5
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop6
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop7
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop8
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop9
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop10
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop11
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop12
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop13
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop14
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop15
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop16
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop17
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop18
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop19
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop20
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop21
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop22
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop23
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop24
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop25
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop26
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop27
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop28
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop29
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop30
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))
local args = {
    [1] = workspace.Areas.Arctic.Hoops.Hoop31
}

game:GetService("ReplicatedStorage").Events.Pickup:FireServer(unpack(args))

wait()
end
end)
--AFK .GUI.
--win:Tab(title <string>)
local tab = win:Tab("Training")

--tab:Section(title <string>)
local sec = tab:Section("TrainingClick")

--AFK .GUI.
sec:Button("[{ AFK }]", function()
   wait(0.5)local ba=Instance.new("ScreenGui")
local ca=Instance.new("TextLabel")local da=Instance.new("Frame")
local _b=Instance.new("TextLabel")local ab=Instance.new("TextLabel")ba.Parent=game.CoreGui
ba.ZIndexBehavior=Enum.ZIndexBehavior.Sibling;ca.Parent=ba;ca.Active=true
ca.BackgroundColor3=Color3.new(0.176471,0.176471,0.176471)ca.Draggable=true
ca.Position=UDim2.new(0.698610067,0,0.098096624,0)ca.Size=UDim2.new(0,370,0,52)
ca.Font=Enum.Font.SourceSansSemibold;ca.Text="Anti AFK Script"ca.TextColor3=Color3.new(0,1,1)
ca.TextSize=22;da.Parent=ca
da.BackgroundColor3=Color3.new(0.196078,0.196078,0.196078)da.Position=UDim2.new(0,0,1.0192306,0)
da.Size=UDim2.new(0,370,0,107)_b.Parent=da
_b.BackgroundColor3=Color3.new(0.176471,0.176471,0.176471)_b.Position=UDim2.new(0,0,0.800455689,0)
_b.Size=UDim2.new(0,370,0,21)_b.Font=Enum.Font.Arial;_b.Text="made by ur mom "
_b.TextColor3=Color3.new(0,1,1)_b.TextSize=20;ab.Parent=da
ab.BackgroundColor3=Color3.new(0.176471,0.176471,0.176471)ab.Position=UDim2.new(0,0,0.158377,0)
ab.Size=UDim2.new(0,370,0,44)ab.Font=Enum.Font.ArialBold;ab.Text="Status: Active"
ab.TextColor3=Color3.new(0,1,1)ab.TextSize=20;local bb=game:service'VirtualUser'
game:service'Players'.LocalPlayer.Idled:connect(function()
bb:CaptureController()bb:ClickButton2(Vector2.new())
ab.Text="Roblox tried to kick u but i kicked him instead"wait(2)ab.Text="Status : Active"end)
end)
