local SolarisLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/Stebulous/solaris-ui-lib/main/source.lua"))()

--[[SolarisLib:New({
  Name - Title of the UI <string>
  FolderToSave - Name of the folder where the UI files will be stored <string>
})]]
local win = SolarisLib:New({
  Name = "Boss Fighting Simulator",
  FolderToSave = "SolarisLibStuff"
})

--win:Tab(title <string>)
local tab = win:Tab("Auto Farm")

--tab:Section(title <string>)
local sec = tab:Section("Auto Farm")

--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local toggle = sec:Toggle("Auto Power", false,"Toggle", function(t)
  _G.Power = t
while _G.Power == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character:FindFirstChild("Gold Naginata")
}

game:GetService("ReplicatedStorage").Remotes.Power:FireServer(unpack(args))

wait()
end
end)

local toggle = sec:Toggle("Auto Sell", false,"Toggle", function(t)
  _G.Sell = t
while _G.Sell == true do
    -- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").Remotes.SellPower:InvokeServer()

wait()
end
end)
--Kill_Boss ALL
--win:Tab(title <string>)
local tab = win:Tab("Auto Boss _All")

--tab:Section(title <string>)
local sec = tab:Section("Boss _All")
--Noob
local toggle = sec:Toggle("Noob", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas.NoobArena.Boss.Noob.LeftLowerLeg
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)

--Knight
local toggle = sec:Toggle("Knight", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas.KnightArena.Boss.Knight.LeftLowerLeg
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)

--Orc
local toggle = sec:Toggle("Orc", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas.OrcArena.Boss.Orc.LeftLowerLeg
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)

--Wizard
local toggle = sec:Toggle("Wizard", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas.WizardArena.Boss.Wizard.RightLeg
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)

--Pirate
local toggle = sec:Toggle("Pirate", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas.PirateArena.Boss.Pirate.LeftLowerLeg
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)

--Ninja
local toggle = sec:Toggle("Ninja", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas.NinjaArena.Boss.Ninja.UpperTorso
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)

--Undead
local toggle = sec:Toggle("Undead", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas.UndeadArena.Boss.Undead.LowerTorso
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)

--Ice King
local toggle = sec:Toggle("Ice King", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas.IceKingArena.Boss:FindFirstChild("Ice King").LeftFoot
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)

--Zeus
local toggle = sec:Toggle("Zeus", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas.ZeusArena.Boss.Zeus.LeftLowerLeg
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)

--Black Knight
local toggle = sec:Toggle("Black Knight", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas:FindFirstChild("Black KnightArena").Boss:FindFirstChild("Black Knight").LeftLowerLeg
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)

--Grim Reaper
local toggle = sec:Toggle("Grim Reaper", false,"Toggle", function(t)
  _G.Kill = t
while _G.Kill == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Arenas:FindFirstChild("Grim ReaperArena").Boss:FindFirstChild("Grim Reaper").RightLowerArm
}

game:GetService("ReplicatedStorage").Remotes.Attack:FireServer(unpack(args))

wait()
end
end)
