local SolarisLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/Stebulous/solaris-ui-lib/main/source.lua"))()

--[[SolarisLib:New({
  Name - Title of the UI <string>
  FolderToSave - Name of the folder where the UI files will be stored <string>
})]]
local win = SolarisLib:New({
  Name = "Milk Simulator",
  FolderToSave = "SolarisLibStuff"
})

--win:Tab(title <string>)
local tab = win:Tab("Auto-Farm")

--tab:Section(title <string>)
local sec = tab:Section("Auto Farm")

--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Auto Drink", false,"Toggle", function(t)
  _G.MilkService = t
while _G.MilkService == true do
    -- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").Knit.Services.MilkService.RE.Drink:FireServer()

wait()
end
end)

--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Auto Sell", false,"Toggle", function(t)
  _G.SellService = t
while _G.SellService == true do
    -- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").Knit.Services.SellService.RE.Sell:FireServer()

wait()
end
end)

--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Auto BuyAll_Milk", false,"Toggle", function(t)
  _G.BuyAll = t
while _G.BuyAll == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Milk"
}

game:GetService("ReplicatedStorage").Knit.Services.ShopService.RF.BuyAll:InvokeServer(unpack(args))

wait()
end
end)

--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Auto BuyAll_DNA", false,"Toggle", function(t)
  _G.BuyAll = t
while _G.BuyAll == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "DNA"
}

game:GetService("ReplicatedStorage").Knit.Services.ShopService.RF.BuyAll:InvokeServer(unpack(args))

wait()
end
end)

--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Auto Pickups", false,"Toggle", function(t)
  _G.Pickups = t
while _G.Pickups == true do
    -- Script generated by SimpleSpy - credits to exx#9394

for i,v in pairs(game:GetService("Workspace").Pickups:GetDescendants()) do
    if v.Name == "TouchInterest" then
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = v.Parent.CFrame
end
end
wait(.1)
end
end)

--Teleport--
--win:Tab(title <string>)
local tab = win:Tab("Teleport_All")

--tab:Section(title <string>)
local sec = tab:Section("Teleport")

--Spawn
--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Spawn", false,"Toggle", function(t)
  _G.Teleport = t
while _G.Teleport == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local TweenService = game:GetService("TweenService")

local Tw = TweenService:Create(game.Players.LocalPlayer.Character.HumanoidRootPart, TweenInfo.new(4, Enum.EasingStyle.Linear, Enum.EasingDirection.Out,0,false,0),
{CFrame = CFrame.new(-687.820435, 4.99104309, -1063.68335, 0.328111529, 1.25388242e-08, 0.944638968, 5.13887706e-08, 1, -3.11230757e-08, -0.944638968, 5.87556777e-08, 0.328111529)}):Play()
wait()
end
end)

--CandyLand
--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("CandyLand", false,"Toggle", function(t)
  _G.Teleport = t
while _G.Teleport == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local TweenService = game:GetService("TweenService")

local Tw = TweenService:Create(game.Players.LocalPlayer.Character.HumanoidRootPart, TweenInfo.new(4, Enum.EasingStyle.Linear, Enum.EasingDirection.Out,0,false,0),
{CFrame = CFrame.new(-799.014282, 466.174438, -1070.76367, 0.9817276, 8.58586802e-08, -0.190291807, -8.15108052e-08, 1, 3.06753698e-08, 0.190291807, -1.46040167e-08, 0.9817276)}):Play()
wait()
end
end)

--Beach
--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Beach", false,"Toggle", function(t)
  _G.Teleport = t
while _G.Teleport == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local TweenService = game:GetService("TweenService")

local Tw = TweenService:Create(game.Players.LocalPlayer.Character.HumanoidRootPart, TweenInfo.new(4, Enum.EasingStyle.Linear, Enum.EasingDirection.Out,0,false,0),
{CFrame = CFrame.new(-765.276917, 1174.74146, -993.789062, -0.969246387, 2.22305125e-08, -0.246092349, 1.2336689e-08, 1, 4.17453876e-08, 0.246092349, 3.74256004e-08, -0.969246387)}):Play()
wait()
end
end)

--Space
--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Space", false,"Toggle", function(t)
  _G.Teleport = t
while _G.Teleport == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local TweenService = game:GetService("TweenService")

local Tw = TweenService:Create(game.Players.LocalPlayer.Character.HumanoidRootPart, TweenInfo.new(4, Enum.EasingStyle.Linear, Enum.EasingDirection.Out,0,false,0),
{CFrame = CFrame.new(-668.790039, 1961.29395, -1135.55872, -0.938577712, -3.78486256e-08, -0.345067918, -4.17772945e-08, 1, 3.94882571e-09, 0.345067918, 1.81222841e-08, -0.938577712)}):Play()
wait()
end
end)

--Toy
--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Toy", false,"Toggle", function(t)
  _G.Teleport = t
while _G.Teleport == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local TweenService = game:GetService("TweenService")

local Tw = TweenService:Create(game.Players.LocalPlayer.Character.HumanoidRootPart, TweenInfo.new(4, Enum.EasingStyle.Linear, Enum.EasingDirection.Out,0,false,0),
{CFrame = CFrame.new(-714.555664, 2598.46924, -895.531128, 0.515173972, 1.00700071e-09, -0.857085645, -3.3025934e-08, 1, -1.86761966e-08, 0.857085645, 3.79275455e-08, 0.515173972)}):Play()
wait()
end
end)

--Cyberpunk
--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Cyberpunk", false,"Toggle", function(t)
  _G.Teleport = t
while _G.Teleport == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local TweenService = game:GetService("TweenService")

local Tw = TweenService:Create(game.Players.LocalPlayer.Character.HumanoidRootPart, TweenInfo.new(4, Enum.EasingStyle.Linear, Enum.EasingDirection.Out,0,false,0),
{CFrame = CFrame.new(-789.654358, 3178.81934, -1097.47034, 0.991698623, -9.35755295e-08, -0.128583819, 1.00075304e-07, 1, 4.40880612e-08, 0.128583819, -5.65901352e-08, 0.991698623)}):Play()
wait()
end
end)

--Russo
--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local Weight = sec:Toggle("Russo", false,"Toggle", function(t)
  _G.Teleport = t
while _G.Teleport == true do
    -- Script generated by SimpleSpy - credits to exx#9394

local TweenService = game:GetService("TweenService")

local Tw = TweenService:Create(game.Players.LocalPlayer.Character.HumanoidRootPart, TweenInfo.new(4, Enum.EasingStyle.Linear, Enum.EasingDirection.Out,0,false,0),
{CFrame = CFrame.new(1517.21289, -173.718353, -708.181213, -0.58871913, -6.02336812e-08, 0.808337688, -8.93777568e-08, 1, 9.42092093e-09, -0.808337688, -6.67011335e-08, -0.58871913)}):Play()
wait()
end
end)

