--UI Sword Simulator Remastered OP--
local SolarisLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/Stebulous/solaris-ui-lib/main/source.lua"))()

--[[SolarisLib:New({
  Name - Title of the UI <string>
  FolderToSave - Name of the folder where the UI files will be stored <string>
})]]
local win = SolarisLib:New({
  Name = "Sword Simulator Remastered",
  FolderToSave = "SolarisLibStuff"
})

--win:Tab(title <string>)
local tab = win:Tab("Auto-Farm")

--tab:Section(title <string>)
local sec = tab:Section("Auto Farm")

--sec:Toggle(title <string>,default <boolean>, flag <string>, callback <function>)
local toggle = sec:Toggle("Auto Power", false,"Toggle", function(t)
  _G.sword = t
while _G.sword == true do
    -- Script generated by SimpleSpy - credits to exx#9394

game:GetService("Players").LocalPlayer.Character.sword.Handle.up.RemoteEvent:FireServer()

wait()
end
end)

--GOD Sword--
sec:Button("Give God", function()
   local args = {
    [1] = "God"
}

game:GetService("Players").LocalPlayer.PlayerGui.Main.SwordGiver.RemoteEvent:FireServer(unpack(args))
end)

--DemigodBlade--
sec:Button("Give Demigod", function()
   local args = {
    [1] = "DemigodBlade"
}

game:GetService("Players").LocalPlayer.PlayerGui.Main.SwordGiver.RemoteEvent:FireServer(unpack(args))
end)
